### ISSUE TITLE
Configure active and inactive tab text style

### ISSUE THREAD

**Issue by MurzNN** [meph1570/treestyletab#3]
Sometimes tab title text on colorized tabs looks bad. Will be good to configure active and inactive tab text style (Font weight, color, shadow) - can you add this feature?

**Comment by meph1570** [comment]
That is possible out of the box.

I have these extra style rules, which make the current tab text bold.

```css
.tab.active {
  font-weight: bold;
}

.tab.active .label {
  color: black !important;
}
```
